openapi: 3.0.0
info:
  title: Ecommerce app
  description: a backend api for ecommerce app
  version: 1.1.0
  contact:
    email: vatsalparmar33@gmail.com
    url: "https:google.com"

servers:
  - url: "http://localhost:3000/api/v1"
    description: for localhost - regular
  - url: "https://localhost:3000/api/v1"
    description: for localhost -secure

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /:
    get:
      tags:
        - Greet
      summary: returns a greet message
      responses:
        200:
          description: all good
          content:
            application/json:
              schema:
                type: string
                example: "hello world"
        400:
          description: Bad request
        500:
          description: internal server error
